### ISSUE TITLE
compatibility issue with foam-extend-5.0

### ISSUE THREAD

**Issue by ma-tri-x** [technoC0re/acousticCavitationOpenFOAM#1]
Hi Sergey,
with the new ubuntu versions the foam-extend-4.1 does not compile anymore and your code unfortunately fails to compile under foam-extend-5.0. For 5.0 they did a major syntax change in the topoChangerFvMesh/topoChangerFvMeshLoadBalanceTemplates.C and the like where they seem to have gotten rid of the evalateCoupled()-function...
Is there any solution to compile your code on 5.0? On our university cluster only 5.0 is installed... Thanks a lot !!
Max

**Comment by sergeylesnik** [comment]
Hi Max,
nice to hear from you! I haven't tried to compile it with fe50, yet. Cannot promise you a solution but I'll look into it next week, because this one is very busy.
Sergey

**Comment by ma-tri-x** [comment]
Hi Sergey!
Thanks a lot! Your former colleague P. Höhn found out that 
> es scheint .evaluateCoupled wurde durch die Funktion updateCoupledPatchFields ersetzt.

so maybe this helps even to port it to fext-5.0?
All the best,
Max

**Comment by ma-tri-x** [comment]
Hi Sergey,
actually, this did the trick. So you can close this issue.
replace
`evaluateCoupled`
with
`updateCoupledPatchFields`
in
`src/dynamicMesh/myTopoChangerFvMesh/topoChangerFvMesh/topoChangerFvMeshLoadBalance.C`
and it compiles.

Best,
Max

**Comment by sergeylesnik** [comment]
Hi Max,
thank you and Patrick for the update. I pushed the change and run a test successfully. Can you confirm that it also works for your cases?
